### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by emckean** [gilt/cloudwatch-elk#4]
Hi! This tool looks exactly like what I need, but I'm not very familiar with Java and I'm getting this error: 
here's my command: 
`groovy -d cloudwatch_elk.groovy -g '/var/log/haproxy.log' -n 'api-haproxy' -f '01/01/2018 08:00' -t '24/01/2018 09:00'`
Caught: java.lang.IllegalArgumentException
java.lang.IllegalArgumentException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2725)
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3770)
	at groovy.lang.MetaClassImpl.setProperties(MetaClassImpl.java:1747)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$NoParamSite.callConstructor(ConstructorSite.java:125)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at cloudwatch_elk.main(cloudwatch_elk.groovy:243)
	at cloudwatch_elk$main.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at cloudwatch_elk.run(cloudwatch_elk.groovy:248)
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:263)
	at groovy.lang.GroovyShell.run(GroovyShell.java:518)
	at groovy.lang.GroovyShell.run(GroovyShell.java:507)
	at groovy.ui.GroovyMain.processOnce(GroovyMain.java:590)
	at groovy.ui.GroovyMain.run(GroovyMain.java:321)
	at groovy.ui.GroovyMain.process(GroovyMain.java:307)
	at groovy.ui.GroovyMain.processArgs(GroovyMain.java:126)
	at groovy.ui.GroovyMain.main(GroovyMain.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:109)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:131)

I'm wondering if the issue is that 'api-haproxy' is a *log stream* and not an EC2 instance?

**Comment by fabriziofortino** [comment]
Thank you for raising  this. There was a bug in the cli that has been fixed.
`-n` has to be the tag `name` of your instances. Most of the times this is the same as log stream, so it should work.
